INFO:root:Looking for config at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\etc\ncpa.cfg
INFO:root:Looking for plugins at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:root:This is indeed the new one
INFO:root:Looking for config at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\etc\ncpa.cfg
INFO:root:Looking for plugins at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:root:This is indeed the new one
INFO:root:Looking for config at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\etc\ncpa.cfg
INFO:root:Looking for plugins at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:root:This is indeed the new one
INFO:werkzeug: * Running on http://0.0.0.0:5693/
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
ERROR:root:list index out of range
Traceback (most recent call last):
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\server.py", line 107, in api
    response = psapi.getter(accessor, listener.config['iconfig'].get('plugin directives', 'plugin_path'))
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\psapi.py", line 165, in getter
    if path[0] == 'api':
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [24/May/2013 11:13:41] "GET /api/?token=brody HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 11:13:41] "GET /error/Referencing%20node%20that%20does%20not%20exist. HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 11:13:41] "GET /favicon.ico HTTP/1.1" 404 -
INFO:root:Looking for config at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\etc\ncpa.cfg
INFO:root:Looking for plugins at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:root:This is indeed the new one
INFO:werkzeug: * Running on http://0.0.0.0:5693/
INFO:root:Looking for config at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\etc\ncpa.cfg
INFO:root:Looking for plugins at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:root:This is indeed the new one
INFO:werkzeug: * Running on http://0.0.0.0:5693/
INFO:root:Looking for config at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\etc\ncpa.cfg
INFO:root:Looking for plugins at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:root:This is indeed the new one
INFO:werkzeug: * Running on http://0.0.0.0:5693/
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:05:24] "GET /api/ HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:05:24] "GET /error/Incorrect%20credentials%20given. HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:05:24] "GET /favicon.ico HTTP/1.1" 404 -
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
ERROR:root:list index out of range
Traceback (most recent call last):
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\server.py", line 107, in api
    response = psapi.getter(accessor, listener.config['iconfig'].get('plugin directives', 'plugin_path'))
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\psapi.py", line 165, in getter
    if path[0] == 'api':
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:05:50] "GET /api/?token=brody HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:05:51] "GET /error/Referencing%20node%20that%20does%20not%20exist. HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:05:51] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:05:51] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:06:20] "GET /api/ HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:06:20] "GET /error/Incorrect%20credentials%20given. HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:06:20] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:09:57] "GET /error/Incorrect%20credentials%20given. HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:09:57] "GET /favicon.ico HTTP/1.1" 404 -
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
ERROR:root:list index out of range
Traceback (most recent call last):
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\server.py", line 107, in api
    response = psapi.getter(accessor, listener.config['iconfig'].get('plugin directives', 'plugin_path'))
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\psapi.py", line 165, in getter
    if path[0] == 'api':
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:10:04] "GET /api/?token=brody HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:10:04] "GET /error/Referencing%20node%20that%20does%20not%20exist. HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:10:04] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:10:04] "GET /favicon.ico HTTP/1.1" 404 -
INFO:root:Looking for config at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\etc\ncpa.cfg
INFO:root:Looking for plugins at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:root:This is indeed the new one
INFO:werkzeug: * Running on http://0.0.0.0:5693/
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
ERROR:root:list index out of range
Traceback (most recent call last):
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\server.py", line 107, in api
    response = psapi.getter(accessor, listener.config['iconfig'].get('plugin directives', 'plugin_path'))
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\psapi.py", line 165, in getter
    if len(path) > 1  and path[0] == 'api':
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:13:34] "GET /api/?token=brody HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:13:34] "GET /error/Referencing%20node%20that%20does%20not%20exist. HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:13:34] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:13:35] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:13:37] "GET /favicon.ico HTTP/1.1" 404 -
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:13:43] "GET /api/cpu?token=brody HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:13:43] "GET /favicon.ico HTTP/1.1" 404 -
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:16:37] "GET /api/cpu?token=brody HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:16:37] "GET /favicon.ico HTTP/1.1" 404 -
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:17:01] "GET /api/cpu?token=brody HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:17:01] "GET /favicon.ico HTTP/1.1" 404 -
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:18:22] "GET /api/cpu?token=brody HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:18:22] "GET /favicon.ico HTTP/1.1" 404 -
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
ERROR:root:list index out of range
Traceback (most recent call last):
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\server.py", line 107, in api
    response = psapi.getter(accessor, listener.config['iconfig'].get('plugin directives', 'plugin_path'))
  File "C:\Users\nscott\Documents\SVN\projects\ncpa\agent\listener\psapi.py", line 165, in getter
    if len(path) > 1  and path[0] == 'api':
IndexError: list index out of range
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:18:29] "GET /api/?token=brody HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:18:29] "GET /error/Referencing%20node%20that%20does%20not%20exist. HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:18:29] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:18:39] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:19:19] "GET /error/Referencing%20node%20that%20does%20not%20exist. HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:19:19] "GET /favicon.ico HTTP/1.1" 404 -
INFO:root:Looking for config at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\etc\ncpa.cfg
INFO:root:Looking for plugins at: C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:root:This is indeed the new one
INFO:werkzeug: * Running on http://0.0.0.0:5693/
DEBUG:root:Using C:\Users\nscott\Documents\SVN\projects\ncpa\agent\plugins/
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:22:10] "GET /api/?token=brody HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:22:10] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [24/May/2013 13:22:13] "GET /favicon.ico HTTP/1.1" 404 -
